version: '3.8'

services:
  balancer:
    build: .
    container_name: balancer
    ports:
      - "${PORT}:8080"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml:ro
    environment:
      - PORT=${PORT}
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clients
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_clients:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d clients'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  mock1:
    build:
      context: ./test_utils
    container_name: mock1
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - NAME=M1
    networks:
      - internal

  mock2:
    build:
      context: ./test_utils
    container_name: mock2
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - NAME=M2
    networks:
      - internal

  mock3:
    build:
      context: ./test_utils
    container_name: mock3
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - NAME=M3
    networks:
      - internal

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  postgres_data_clients: