// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "schemes": ["http"],
  "swagger": "2.0",
  "info": {
    "description": "API для регистрации, авторизации и работы с задачами.",
    "title": "Task Management API",
    "contact": {},
    "version": "1.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/auth/register": {
      "post": {
        "description": "Register a new user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "Register",
        "parameters": [
          {
            "description": "User registration data",
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User registered successfully",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "description": "Login with existing user credentials",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "Login",
        "parameters": [
          {
            "description": "User login data",
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "description": "Refresh access token using refresh token",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "Refresh token",
        "parameters": [
          {
            "description": "Refresh token data",
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RefreshRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Token refreshed successfully",
            "schema": {
              "$ref": "#/definitions/AuthResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
	"/api/chat": {
	  "get": {
		"summary": "Получить историю чата пользователя",
		"tags": ["Chat"],
		"produces": ["application/json"],
		"responses": {
		  "200": {
			"description": "Успешный запрос",
			"schema": {
			  "$ref": "#/definitions/ChatResponse"
			}
		  },
		  "401": {
			"description": "Не авторизован"
		  },
		  "500": {
			"description": "Ошибка сервера"
		  }
		}
	  },
	  "post": {
		"summary": "Отправить сообщение",
		"tags": ["Chat"],
		"consumes": ["application/json"],
		"produces": ["application/json"],
		"parameters": [
		  {
			"name": "body",
			"in": "body",
			"required": true,
			"description": "Данные сообщения",
			"schema": {
			  "$ref": "#/definitions/SendMsgRequest"
			}
		  }
		],
		"responses": {
		  "200": {
			"description": "Сообщение успешно отправлено",
			"schema": {
			  "type": "object",
			  "properties": {
				"status": {
				  "type": "string",
				  "example": "ok"
				}
			  }
			}
		  },
		  "400": {
			"description": "Неверный формат запроса"
		  },
		  "401": {
			"description": "Не авторизован"
		  },
		  "500": {
			"description": "Ошибка сервера"
		  }
		}
	  }
	}
  },
  "definitions": {
    "RegisterRequest": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "LoginRequest": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "TaskRequest": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Task"
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "difficulty": {
          "type": "integer"
        }
      }
    },
    "AuthResponse": {
      "type": "object",
      "properties": {
        "access_token": {
          "type": "string"
        },
        "refresh_token": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",

      "name": "Authorization",
      "in": "header"
    }
  }
}
`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API liquid streams",
	Description:      "This is a sample server for liquid stream calculations.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
