// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"github.com/swaggo/swag"
	"os"
)

var port = os.Getenv("PORT")

var docTemplate = `{
  "schemes": ["http"],
  "swagger": "2.0",
  "info": {
    "description": "API для управления клиентами и балансировкой нагрузки.",
    "title": "Balancer API",
    "contact": {},
    "version": "1.0"
  },
  "host": "localhost:` + port + `",
  "basePath": "/",
  "securityDefinitions": {
    "ApiKeyAuth": {
      "type": "apiKey",
      "in": "header",
      "name": "X-Api-Key"
    }
  },
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "paths": {
    "/clients/{id}": {
      "get": {
        "description": "Получить информацию о клиенте по ID",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "clients"
        ],
        "summary": "Получить клиента",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID клиента",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Информация о клиенте",
            "schema": {
              "$ref": "#/definitions/Client"
            }
          },
          "404": {
            "description": "Клиент не найден"
          },
          "500": {
            "description": "Ошибка сервера"
          }
        }
      },
      "delete": {
        "description": "Удалить клиента по ID",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "clients"
        ],
        "summary": "Удалить клиента",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID клиента",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Клиент успешно удален"
          },
          "404": {
            "description": "Клиент не найден"
          },
          "500": {
            "description": "Ошибка сервера"
          }
        }
      }
    },
    "/clients": {
      "post": {
        "description": "Создать нового клиента",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "clients"
        ],
        "summary": "Создать клиента",
        "parameters": [
          {
            "name": "client",
            "in": "body",
            "description": "Данные клиента",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Client"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Клиент успешно создан",
            "schema": {
              "$ref": "#/definitions/Client"
            }
          },
          "400": {
            "description": "Некорректные данные запроса"
          },
          "500": {
            "description": "Ошибка сервера"
          }
        }
      },
      "put": {
        "description": "Обновить данные клиента",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "clients"
        ],
        "summary": "Обновить клиента",
        "parameters": [
          {
            "name": "client",
            "in": "body",
            "description": "Данные для обновления клиента",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Client"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Данные клиента обновлены",
            "schema": {
              "$ref": "#/definitions/Client"
            }
          },
          "404": {
            "description": "Клиент не найден"
          },
          "500": {
            "description": "Ошибка сервера"
          }
        }
      }
    },
    "/api": {
      "get": {
        "summary": "Проксирование запросов на серверы балансировщика",
        "tags": ["proxy"],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Успешное проксирование",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "ok"
                }
              }
            }
          },
          "500": {
            "description": "Ошибка сервера"
          }
        }
      }
    }
  },
  "definitions": {
    "Client": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "example": "12345"
        },
        "rate": {
          "type": "integer",
          "example": 10
        },
        "capacity": {
          "type": "integer",
          "example": 100
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "example": 429
        },
        "message": {
          "type": "string",
          "example": "Rate limit exceeded"
        }
      }
    }
  }
}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:" + port,
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Balancer API",
	Description:      "API для управления клиентами и балансировкой нагрузки.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
